import { CheckCircle2, FileUser, ShieldCheck } from "lucide-react";
import { LoginForm } from "@/components/login-form";
import { ThemeToggle } from "@/components/theme-toggle";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function LoginPage() {
  return <main className="dashboard-grid grid min-h-dvh lg:grid-cols-[1.05fr_.95fr]">
    <section className="hidden bg-sidebar p-12 text-sidebar-foreground lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-sidebar-primary text-sidebar-primary-foreground"><FileUser className="size-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sidebar-foreground/55">Career</p><p className="font-semibold">Autopilot</p></div></div><div className="max-w-lg"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-sidebar-primary">Your private career workspace</p><h1 className="mt-4 text-4xl font-semibold leading-tight tracking-tight">Spend your time deciding, not searching.</h1><p className="mt-5 text-lg leading-8 text-sidebar-foreground/65">Relevant opportunities arrive filtered, ranked, and ready for your review. You stay in control of every application.</p><ul className="mt-8 space-y-4 text-sm"><li className="flex items-center gap-3"><CheckCircle2 className="size-5 text-sidebar-primary" />Expired and duplicate jobs removed</li><li className="flex items-center gap-3"><CheckCircle2 className="size-5 text-sidebar-primary" />Previously shown jobs never resurface</li><li className="flex items-center gap-3"><CheckCircle2 className="size-5 text-sidebar-primary" />Application material grounded in your real resume</li></ul></div><p className="text-xs text-sidebar-foreground/45">Single-user · Encrypted session · No automatic submissions</p></section>
    <section className="relative flex items-center justify-center p-4 sm:p-8"><div className="absolute right-4 top-4"><ThemeToggle /></div><Card className="w-full max-w-md shadow-xl shadow-primary/5"><CardHeader className="space-y-3 p-6 sm:p-8"><span className="grid size-11 place-items-center rounded-xl bg-accent text-accent-foreground lg:hidden"><FileUser className="size-5" /></span><div><CardTitle className="text-2xl">Welcome back, Lakshit</CardTitle><CardDescription className="mt-2 text-base leading-6">Sign in to review today’s opportunities and actions.</CardDescription></div></CardHeader><CardContent className="px-6 pb-6 sm:px-8 sm:pb-8"><LoginForm /><p className="mt-6 flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4" />Your password stays on the server.</p></CardContent></Card></section>
  </main>;
}
